id: code-diff
name: Code Diff Output
version: 1.0.0
tags: ["coding", "diff", "patch"]
triggers:
  keywords: ["diff", "patch", "apply_patch", "apply patch", "cambia", "modifica", "arregla"]
  regex: ["```file:"]
token_budget: 220
priority: 80
safety:
  network: false
  filesystem_write: false
  shell: false
requires_approval: false
source: local:vortex-core

